### ISSUE TITLE
On Join Server

### ISSUE THREAD

**Issue by danielslux** [ic3bug/Simple-3D-Multiplayer#5]
When Joining a server, the editor returns error, This is most likely due to a update in the godot software. I cannot update this myself as I don't have much information regarding updating the code.
If you could update the code so it works for the newest version that would be awesome! 

Thanks! 

------- Here is what the game returns on joining a game ------
E 0:00:08.511   connect: Signal 'network_peer_connected' is already connected to given method '_on_peer_connected' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
  <Stack Trace> main.gd:49 @ _on_connect_pressed()

E 0:00:08.525   connect: Signal 'network_peer_disconnected' is already connected to given method '_on_peer_disconnected' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
  <Stack Trace> main.gd:50 @ _on_connect_pressed()

E 0:00:08.536   connect: Signal 'connected_to_server' is already connected to given method '_on_connected_to_server' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
  <Stack Trace> main.gd:51 @ _on_connect_pressed()

E 0:00:08.548   connect: Signal 'connection_failed' is already connected to given method '_on_connection_failed' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
  <Stack Trace> main.gd:52 @ _on_connect_pressed()

E 0:00:08.561   connect: Signal 'server_disconnected' is already connected to given method '_on_server_disconnected' in that object.
  <C++ Error>   Method failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1515 @ connect()
  <Stack Trace> main.gd:53 @ _on_connect_pressed()

----------------------------------
this is the file that returns error
----------------------------------

main.gd

---------------------------------

Thanks!

**Comment by ic3bug** [comment]
Which version of Godot are you using?

**Comment by danielslux** [comment]
This Issue was fixed, Replaced ip with IP.
I do however wish to contact you via Twitter, ic3bug. 
My user is @DanielsLux_
Thanks!
